version: '3.7'

services: 
  redis:
    image: redis:6
    environment:
      - REDIS_PASSWORD=redis
    restart: always
    volumes:
      - ./data/redis:/data
  db:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=postgres
    restart: always
    volumes:
      - ./data/pg:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis
    depends_on:
      - db
      - redis
    restart: always
